# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: iamzayn19.Kara
PackageVersion: 0.1.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: kara-v0.1.0-x86_64-pc-windows-msvc\kara.exe
    PortableCommandAlias: kara
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/iamzayn19/kara/releases/download/v0.1.0/kara-v0.1.0-x86_64-pc-windows-msvc.zip
    InstallerSha256: 9014E550120E6145C8D0AAB7F3EA5BC19A3DB1A680D200A2BB98F4DC0D8668F7
  - Architecture: arm64
    InstallerUrl: https://github.com/iamzayn19/kara/releases/download/v0.1.0/kara-v0.1.0-aarch64-pc-windows-msvc.zip
    InstallerSha256: 37AF51DBE08A927628F51F1EA74F9DF7F3DD3DE3135CDDA73F7AB2B656A8546B
ManifestType: installer
ManifestVersion: 1.6.0
